name: formula1_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  firebase_core: ^2.30.1
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.4
  google_sign_in:  ^5.2.1
  cloud_firestore: ^4.17.2
  rxdart: ^0.27.7
  provider: ^6.1.2
  like_button: 2.0.5
  favorite_button: 0.0.4
  share: ^2.0.4
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/icons/teams_icon.png
    - assets/icons/user_icon.png
    - assets/icons/news_icon.png
