// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexaX8hDkpB4P41g_3KpLrRo5i6WneOWw',
    appId: '1:57033051103:web:f0637e743fd7c91502d26a',
    messagingSenderId: '57033051103',
    projectId: 'f1-fan-site-next-js',
    authDomain: 'f1-fan-site-next-js.firebaseapp.com',
    storageBucket: 'f1-fan-site-next-js.appspot.com',
    measurementId: 'G-1XZG86VHPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-M9zFviv9IsxTpPQoaRPGF7T-Is0Wzc0',
    appId: '1:57033051103:android:ea324373e687e48602d26a',
    messagingSenderId: '57033051103',
    projectId: 'f1-fan-site-next-js',
    storageBucket: 'f1-fan-site-next-js.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAek18ssROpfP7oqNLL8nZc963YYp6JbDA',
    appId: '1:57033051103:ios:b462955f9b1bfb3b02d26a',
    messagingSenderId: '57033051103',
    projectId: 'f1-fan-site-next-js',
    storageBucket: 'f1-fan-site-next-js.appspot.com',
    iosClientId: '57033051103-4natuq1p6fjvf4j39o380a609ooofvj2.apps.googleusercontent.com',
    iosBundleId: 'org.mycompany.formula1App',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAek18ssROpfP7oqNLL8nZc963YYp6JbDA',
    appId: '1:57033051103:ios:b462955f9b1bfb3b02d26a',
    messagingSenderId: '57033051103',
    projectId: 'f1-fan-site-next-js',
    storageBucket: 'f1-fan-site-next-js.appspot.com',
    iosClientId: '57033051103-4natuq1p6fjvf4j39o380a609ooofvj2.apps.googleusercontent.com',
    iosBundleId: 'org.mycompany.formula1App',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDexaX8hDkpB4P41g_3KpLrRo5i6WneOWw',
    appId: '1:57033051103:web:3be258c81842a20302d26a',
    messagingSenderId: '57033051103',
    projectId: 'f1-fan-site-next-js',
    authDomain: 'f1-fan-site-next-js.firebaseapp.com',
    storageBucket: 'f1-fan-site-next-js.appspot.com',
    measurementId: 'G-42N2LNQJF0',
  );
}
